### PR TITLE
[UPDATE]: Upgrade clubs theme to Hashi 2.x

### PR DESCRIPTION
**Pull request by MatteuSan**

### CODE REVIEW

**Comment by MatteuSan** [comment]
hallo! can everyone check on the changes i've made. if changes are necessary please let me know so i can work on it asap. thanks!

**Review by yashdesu — APPROVED** [review]
LGTM!

**Comment by MatteuSan** [comment]
wait im gonna fix a few things in hashi 

sorry for the minor inconvenience :<

**Review by aggre — APPROVED** [review]
Nice changes!

**Pull request merged**
